var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                    xxxxx                       ",
   "                                                    x!!!x                       ",
   "                                                     xvx                        ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                            o o                                                 ",
   "                           xxxxx                                          xxxxxx",
   "                                   xxxx                    o                xxxx",
   "                    xxx                   o      xxx     xxx                xxxx",
   "                  xxxxx                  xxxx    xxx     xxx                xxxx",
   "                xxxxxxx                          xxx     xxx                xxxx",
   "     @         xxxxxxxx    xe          xe        xxx     xxx      o  o      xxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx     xxxx   xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxhhhxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxx!xxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxx",
   "xxxxxxxx!xxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxx",
   "       x!x            xx!v!xx                                      xx!xx       xx",
   "       xvx                                                         x!!!x       xx",
   "                                                                   x!|!x       xx",
   "                                                                               xx",
   "                                      xx                                       xx",
   "                                           xxx                                 xx",
   "o                        o                                                     xx",
   "xx      o               xxx                                                    xx",
   "xx    xxxx      xxxx          xxxxx                xxxxxxxxxxxx                xx",
   "xxhhhhxxxxhhhhhhxxxxhhhhhhhhhhxxxxxhhhhhhhhhhhhhhhhxxxxxxxxxxxxxx              xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        hhhhxx",
   "x                                                          xxxxxxxxxx     hxxxxxx",
   "x                                                          xxxxx         xxxxxxxx",
   "x o                                                        xxxxx       o xxxxxxxx",
   "xxxxxx                                        o            xxxxx      xxxxxxxxxxx",
   "x                 o      xx            xx    xxxx          xxxxx         xxxxxxxx",
   "x        xx     xxxxx          xxxxx                xxxx   xxxxx o       xxxxxxxx",
   "x        xx!!!!!xxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!xxxx   xxxxxxxx      xxxxxxxx",
   "x      xxxx!!!!!xxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!xxxx   xxxxx         xxxxxxxx",
   "x   xxxxxxx!!!!!xxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!xxxx              xxxxxxxxxxx",
   "x@  xxxxxxx!!!!!xxxxx!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!xxxx                 xxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " @        xxxx!!!!!xxxxxxxxxxx!!!!!xxx!!!!!xxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxx    xxxx!!!!!xxxxxxxxxxxx!v!xxxxx!v!xxxxx!v!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxx    xxxx!!!!!xx                                                                 xxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxx    xxxx!!!!!xx                                     o       o       o           xxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxxo   xxxxx!!!xxx                                xe                        x      xxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxx    xxxxxx|xxxx                                                                 xxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxx    xxx                                                                         xxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxx    xxx                                         xxxxxx   xxxxxx   xxxxx         xxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxx    xxx          x e                            xxxxxxhhhxxxxxxhhhxxxxx         xxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxx    xxx   o  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxx    xxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxx",
   "x!xxxx    xxx        xxxx                |          |         |           |           xxxxxxxxxxxxxxxxxxxxxxxx",
   "xvxxxx   oxxxxx      xxxx                                                             xxxxxxxxxxxxxxxxxxxxxxxx",
   "x xxxx    xxx        xxxx                                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x xxxx    xxx      xxxxxx           |          |         |          |            xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x xxxx    xxx   o    xxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x xxxx    xxx        xxxx             x                            x             xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x         xxxxx      xxxx             x                            xo            xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x         xxx        xxxx             x o                        o x        x    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x    xxxxxxxx        xxxx             xxxxxx             xxxxxxxxxxxxxx     x                                x",
   "x                  xxxxxx             x             e          x!!!x        x                                x",
   "xo              o    xxxx                                      x!!!x        x                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxx                         xxxx         x!v!x      xxx                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxx                            x        x                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhhhhhxxxx                            x        x             o        o         x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      xxx      x                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            x        x                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxx                      x         o                      x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                   xxx                  o       o     x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     x xx    xxxxx    xxxxx   xxxxx   x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    xxxxxxxxxxxxxxxxxxhxx hh xxxxx hh xxxxx h xxxxx h x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            xxxxxxxxxx                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxxxhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
